- name: Check if httpd is installed on RHEL servers
  hosts: 10.20.103.100
  become: yes
  tasks:
    - name: Check if httpd package is installed
      ansible.builtin.shell: rpm -q httpd
      register: httpd_check
      ignore_errors: yes

    - name: Report httpd installation status
      debug:
        msg: >
          {% if httpd_check.rc == 0 %}
            httpd is installed.
          {% else %}
            httpd is NOT installed.
          {% endif %}
