- name: Install Apache httpd on RHEL servers
  hosts: 10.20.103.114
  become: yes
  tasks:
    - name: Ensure httpd is installed
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Ensure httpd is enabled to start on boot
      ansible.builtin.systemd:
        name: httpd
        enabled: yes

    - name: Ensure httpd is started
      ansible.builtin.systemd:
        name: httpd
        state: started
