- name: Open HTTP and HTTPS ports in firewalld on RHEL
  hosts: 10.20.103.100
  become: yes
  tasks:

    - name: Ensure firewalld is installed
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Ensure firewalld is running and enabled
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Open HTTP (port 80)
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Open HTTPS (port 443)
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled
        immediate: true
